<?php

return [
    'attachments' => [
        'disk' => env('WBS_ATTACHMENTS_DISK', 'attachments'),
        'max_kilobytes' => (int) env('WBS_ATTACHMENT_MAX_KILOBYTES', 20480),
        'max_files' => 10,
        'accepted_mimetypes' => [
            'application/pdf',
            'image/jpeg',
            'image/png',
            'image/webp',
            'text/plain',
            'text/csv',
            'application/msword',
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            'application/vnd.ms-excel',
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'application/vnd.ms-powerpoint',
            'application/vnd.openxmlformats-officedocument.presentationml.presentation',
            'application/zip',
            'application/x-zip-compressed',
        ],
    ],
    'roles' => [
        'reporter' => 'Reporter',
        'supervisor_of_verificator' => 'Verification Supervisor',
        'verificator' => 'Verification Officer',
        'supervisor_of_investigator' => 'Investigation Supervisor',
        'investigator' => 'Investigator',
        'director' => 'Director',
        'system_administrator' => 'System Administrator',
    ],
    'internal_roles' => [
        'supervisor_of_verificator',
        'verificator',
        'supervisor_of_investigator',
        'investigator',
        'director',
        'system_administrator',
    ],
    'categories' => [
        'kpk_report' => 'KPK whistleblowing report',
        'bribery' => 'Bribery and gratuities',
        'procurement' => 'Procurement fraud',
        'fraud' => 'Financial fraud',
        'abuse_of_authority' => 'Abuse of authority',
        'conflict_of_interest' => 'Conflict of interest',
        'harassment' => 'Harassment or misconduct',
        'retaliation' => 'Retaliation against reporter',
        'other' => 'Other governance concern',
    ],
    'governance_tags' => [
        'official-abuse' => 'Abuse of office',
        'state-loss' => 'State financial loss',
        'procurement' => 'Procurement irregularity',
        'bribery' => 'Bribery indication',
        'gratuity' => 'Gratuity indication',
        'conflict-of-interest' => 'Conflict of interest',
        'obstruction' => 'Obstruction risk',
        'retaliation-risk' => 'Retaliation risk',
        'conflict-sensitive' => 'Conflict-sensitive matter',
        'leadership' => 'Leadership escalation',
        'financial-loss' => 'Potential financial loss',
        'data-integrity' => 'Data integrity concern',
    ],
    'confidentiality_levels' => [
        'anonymous' => 'Anonymous reporter',
        'identified' => 'Registered reporter',
    ],
    'reported_party_classifications' => [
        'state_official' => 'State official',
        'civil_servant' => 'Civil servant',
        'law_enforcement' => 'Law enforcement officer',
        'other' => 'Other',
    ],
    'corruption_aspect_tags' => [
        'bribery' => 'Bribery',
        'gratuity' => 'Gratuity',
        'procurement_irregularity' => 'Procurement irregularity',
        'abuse_of_authority' => 'Abuse of authority',
        'conflict_of_interest' => 'Conflict of interest',
        'state_financial_loss' => 'State financial loss',
        'obstruction_of_justice' => 'Obstruction of justice',
        'other' => 'Other corruption aspect',
    ],
    'verification_recommendations' => [
        'review' => 'Investigation',
        'forward' => 'Forward',
        'archive' => 'Archive',
    ],
    'review_recommendations' => [
        'internal_forwarding' => 'Forward internally',
        'external_forwarding' => 'Forward externally',
        'archive' => 'Archive',
    ],
    'delict_tags' => [
        'state_financial_loss' => 'State financial loss',
        'bribery' => 'Bribery',
        'embezzlement_in_office' => 'Embezzlement in office',
        'extortion' => 'Extortion',
        'fraudulent_act' => 'Fraudulent act',
        'procurement_conflict_of_interest' => 'Conflict of interest in procurement',
        'gratification' => 'Gratification',
        'obstruction_of_justice' => 'Obstruction of justice',
        'other' => 'Other',
    ],
    'corruption_articles' => [
        'article_2_31_1999' => 'Law 31/1999 Article 2',
        'article_3_31_1999' => 'Law 31/1999 Article 3',
        'article_5_31_1999' => 'Law 31/1999 Article 5',
        'article_11_31_1999' => 'Law 31/1999 Article 11',
        'article_12_31_1999' => 'Law 31/1999 Article 12',
        'article_12b_20_2001' => 'Law 20/2001 Article 12B',
        'article_21_31_1999' => 'Law 31/1999 Article 21',
        'article_22_31_1999' => 'Law 31/1999 Article 22',
        'article_23_31_1999' => 'Law 31/1999 Article 23',
        'article_55_criminal_code' => 'Criminal Code Article 55',
    ],
    'months' => [
        '01' => 'January',
        '02' => 'February',
        '03' => 'March',
        '04' => 'April',
        '05' => 'May',
        '06' => 'June',
        '07' => 'July',
        '08' => 'August',
        '09' => 'September',
        '10' => 'October',
        '11' => 'November',
        '12' => 'December',
    ],
    'case_stages' => [
        'submitted' => 'Submitted',
        'screening_closed' => 'Closed during preliminary screening',
        'verification_in_progress' => 'Verification in Progress',
        'verification_review' => 'Verification Approval',
        'verified' => 'Awaiting Investigation Delegation',
        'investigation_in_progress' => 'Investigation in Progress',
        'investigation_review' => 'Investigation Approval',
        'director_review' => 'Director Review',
        'completed' => 'Completed',
    ],
    'governance_principles' => [
        'confidentiality' => 'Protect registered reporter identity while preserving an auditable internal case trail.',
        'traceability' => 'Record every screening, delegation, recommendation, approval, forwarding, archival, and completion step as audit evidence.',
        'segregation' => 'Separate reporter, verification, investigation, direction, and administration duties by role.',
        'timeliness' => 'Track SLAs across verification, investigation, and director decision stages.',
    ],
];
