<?php

return [
    'attachments' => [
        'disk' => env('WBS_ATTACHMENTS_DISK', 'attachments'),
        'max_kilobytes' => (int) env('WBS_ATTACHMENT_MAX_KILOBYTES', 20480),
        'max_files' => 10,
        'accepted_mimetypes' => [
            'application/pdf',
            'image/jpeg',
            'image/png',
            'image/webp',
            'text/plain',
            'text/csv',
            'application/msword',
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            'application/vnd.ms-excel',
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'application/vnd.ms-powerpoint',
            'application/vnd.openxmlformats-officedocument.presentationml.presentation',
            'application/zip',
            'application/x-zip-compressed',
        ],
    ],
    'roles' => [
        'reporter' => 'Reporter',
        'supervisor_of_verificator' => 'Verification Supervisor',
        'verificator' => 'Verification Officer',
        'supervisor_of_investigator' => 'Investigation Supervisor',
        'investigator' => 'Investigator',
        'director' => 'Director',
        'system_administrator' => 'System Administrator',
    ],
    'internal_roles' => [
        'supervisor_of_verificator',
        'verificator',
        'supervisor_of_investigator',
        'investigator',
        'director',
        'system_administrator',
    ],
    'categories' => [
        'bribery' => 'Bribery and gratuities',
        'procurement' => 'Procurement fraud',
        'fraud' => 'Financial fraud',
        'abuse_of_authority' => 'Abuse of authority',
        'conflict_of_interest' => 'Conflict of interest',
        'harassment' => 'Harassment or misconduct',
        'retaliation' => 'Retaliation against reporter',
        'other' => 'Other governance concern',
    ],
    'governance_tags' => [
        'retaliation-risk' => 'Retaliation risk',
        'conflict-sensitive' => 'Conflict-sensitive matter',
        'procurement' => 'Procurement exposure',
        'leadership' => 'Leadership escalation',
        'financial-loss' => 'Potential financial loss',
        'data-integrity' => 'Data integrity concern',
    ],
    'confidentiality_levels' => [
        'anonymous' => 'Anonymous reporter',
        'identified' => 'Identified reporter',
    ],
    'case_stages' => [
        'submitted' => 'Submitted',
        'verification_in_progress' => 'Verification in Progress',
        'verification_review' => 'Verification Review',
        'verified' => 'Verified',
        'investigation_in_progress' => 'Investigation in Progress',
        'investigation_review' => 'Investigation Review',
        'director_review' => 'Director Review',
        'completed' => 'Completed',
    ],
    'governance_principles' => [
        'confidentiality' => 'Require registered reporters while preserving encrypted identity handling and optional anonymous exposure in the workflow.',
        'traceability' => 'Record every delegation, approval, rejection, and completion as audit evidence.',
        'segregation' => 'Separate reporting, verification, investigation, direction, and administration duties by role.',
        'timeliness' => 'Track SLAs across verification, investigation, and director review.',
    ],
];
