services:
  redis:
    image: redis:7-alpine
    container_name: wbs_thesis_redis
    restart: unless-stopped
    profiles: ["cache"]
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata_wbs_thesis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - wbs_thesis

volumes:
  redisdata_wbs_thesis:

networks:
  wbs_thesis:
